export const USER_CONTACT_REQUEST = "USER_CONTACT_REQUEST";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FAIL";

export const GET_CONTACT_REQUEST = "GET_CONTACT_REQUEST";
export const GET_CONTACT_SUCESS = "GET_CONTACT_SUCESS";
export const GET_CONTACT_FAIL = "GET_CONTACT_FAIL";
